function build_learning_visuals(mode)
%BUILD_LEARNING_VISUALS Create explanatory animations from saved results.

arguments
    mode (1, 1) string {mustBeMember(mode, ["all", "preview"])} = "all"
end

project_directory = fileparts(mfilename("fullpath"));
original_directory = pwd;
cleanup_directory = onCleanup(@() cd(original_directory));
cd(project_directory);

results = readtable("simulation_results.csv");
time = results.time_s;
x_simulink = results.x_simulink_m;
theta_simulink = results.theta_simulink_rad;
x_multibody = results.x_multibody_m;
theta_multibody = results.theta_multibody_rad;

colors.garnet = [115, 0, 10] / 255;
colors.atlantic = [70, 106, 159] / 255;
colors.black = [0, 0, 0];
colors.dark_gray = [54, 54, 54] / 255;
colors.medium_gray = [92, 92, 92] / 255;
colors.light_gray = [199, 199, 199] / 255;
colors.pale_gray = [235, 235, 235] / 255;
colors.sand = [255, 242, 227] / 255;
colors.white = [1, 1, 1];

parameters.cart_mass = 2;
parameters.pendulum_mass = 0.5;
parameters.length = 1;
parameters.damping = 0.01;
parameters.gravity = 9.81;

figure_handle = figure( ...
    "Color", colors.white, ...
    "Position", [60, 60, 1600, 900], ...
    "Visible", "off");
graphics = initialize_animation_figure( ...
    figure_handle, time, x_simulink, theta_simulink, ...
    x_multibody, theta_multibody, parameters, colors);

snapshot_times = [0, 2.75, time(find(abs(x_multibody) == max(abs(x_multibody)), 1)), 15];
snapshot_names = [ ...
    "learning_visual_start.png", ...
    "learning_visual_first_swing.png", ...
    "learning_visual_max_displacement.png", ...
    "learning_visual_late_motion.png"];

for index = 1:numel(snapshot_times)
    update_animation_figure( ...
        graphics, snapshot_times(index), time, x_multibody, ...
        theta_multibody, colors, "Snapshot");
    drawnow;
    exportgraphics(figure_handle, snapshot_names(index), "Resolution", 180);
end

if mode == "preview"
    preview_times = linspace(0, 1, 6);
    write_animation( ...
        figure_handle, graphics, preview_times, time, ...
        x_multibody, theta_multibody, colors, ...
        "learning_visual_preview.mp4", 5, "Preview");
else
    full_frame_rate = 30;
    full_times = (time(1):1 / full_frame_rate:time(end)).';
    write_animation( ...
        figure_handle, graphics, full_times, time, ...
        x_multibody, theta_multibody, colors, ...
        "pendulum_cart_full_motion.mp4", full_frame_rate, ...
        "Full 20 s simulation");

    slow_frame_rate = 30;
    slow_motion_factor = 0.5;
    slow_simulation_end = 8;
    slow_times = (0:slow_motion_factor / slow_frame_rate:slow_simulation_end).';
    write_animation( ...
        figure_handle, graphics, slow_times, time, ...
        x_multibody, theta_multibody, colors, ...
        "pendulum_cart_first_swing_slow_motion.mp4", slow_frame_rate, ...
        "First 8 s at 0.5x speed");
end

close(figure_handle);
clear cleanup_directory;
end

function graphics = initialize_animation_figure( ...
        figure_handle, time, x_simulink, theta_simulink, ...
        x_multibody, theta_multibody, parameters, colors)
layout = tiledlayout(figure_handle, 2, 3, ...
    "TileSpacing", "compact", "Padding", "compact");

scene_axes = nexttile(layout, [2, 2]);
hold(scene_axes, "on");
axis(scene_axes, [-1.72, 1.72, -1.27, 1.48]);
axis(scene_axes, "equal");
scene_axes.XTick = [];
scene_axes.YTick = [];
scene_axes.Box = "on";
scene_axes.LineWidth = 1.2;
scene_axes.Color = colors.sand;
scene_axes.FontName = "Times New Roman";

patch(scene_axes, ...
    [-1.72, 1.72, 1.72, -1.72], ...
    [-1.27, -1.27, -0.87, -0.87], ...
    colors.pale_gray, ...
    "EdgeColor", "none");
line(scene_axes, [-1.72, 1.72], [-0.87, -0.87], ...
    "Color", colors.black, "LineWidth", 2);
line(scene_axes, [0, 0], [-0.82, 1.42], ...
    "Color", colors.light_gray, "LineStyle", "--", "LineWidth", 1.2);
text(scene_axes, 0.02, 1.39, "camera center", ...
    "Color", colors.medium_gray, "FontName", "Times New Roman", ...
    "FontSize", 11, "HorizontalAlignment", "left", ...
    "VerticalAlignment", "top");

world_ticks = -3:0.25:3;
major_tick_mask = abs(2 * world_ticks - round(2 * world_ticks)) < 1e-10;
tick_lines = gobjects(size(world_ticks));
tick_labels = gobjects(size(world_ticks));
for index = 1:numel(world_ticks)
    if major_tick_mask(index)
        tick_height = 0.14;
        tick_width = 1.6;
        label_text = sprintf("%+.1f", world_ticks(index));
    else
        tick_height = 0.075;
        tick_width = 0.8;
        label_text = "";
    end
    tick_lines(index) = line(scene_axes, ...
        [world_ticks(index), world_ticks(index)], ...
        [-0.87, -0.87 - tick_height], ...
        "Color", colors.dark_gray, "LineWidth", tick_width);
    tick_labels(index) = text(scene_axes, world_ticks(index), -1.08, label_text, ...
        "Color", colors.dark_gray, "FontName", "Times New Roman", ...
        "FontSize", 10, "HorizontalAlignment", "center", ...
        "VerticalAlignment", "top");
end
text(scene_axes, -1.66, -1.22, "world position ruler, m", ...
    "Color", colors.dark_gray, "FontName", "Times New Roman", ...
    "FontSize", 11, "HorizontalAlignment", "left");

origin_marker = plot(scene_axes, 0, -0.82, "v", ...
    "Color", colors.garnet, "MarkerFaceColor", colors.garnet, ...
    "MarkerSize", 10, "LineWidth", 1.5);
origin_label = text(scene_axes, 0, -0.73, "world origin", ...
    "Color", colors.garnet, "FontName", "Times New Roman", ...
    "FontSize", 10, "FontWeight", "bold", ...
    "HorizontalAlignment", "center", "VerticalAlignment", "bottom");
translation_line = plot(scene_axes, [0, 0], [-0.62, -0.62], ...
    "Color", colors.garnet, "LineWidth", 4, "Marker", "|", ...
    "MarkerSize", 12);
translation_label = text(scene_axes, 0, -0.55, "x(t) = 0.000 m", ...
    "Color", colors.garnet, "FontName", "Times New Roman", ...
    "FontSize", 11, "FontWeight", "bold", ...
    "HorizontalAlignment", "center", "VerticalAlignment", "bottom");

wheel_left = rectangle(scene_axes, ...
    "Position", [-0.27, -0.24, 0.15, 0.15], ...
    "Curvature", [1, 1], "FaceColor", colors.dark_gray, ...
    "EdgeColor", colors.black, "LineWidth", 1.5);
wheel_right = rectangle(scene_axes, ...
    "Position", [0.12, -0.24, 0.15, 0.15], ...
    "Curvature", [1, 1], "FaceColor", colors.dark_gray, ...
    "EdgeColor", colors.black, "LineWidth", 1.5);
wheel_centers = [-0.195, -0.165; 0.195, -0.165];
wheel_radius = 0.075;
wheel_spokes = gobjects(2, 2);
for wheel_index = 1:2
    for spoke_index = 1:2
        wheel_spokes(wheel_index, spoke_index) = line(scene_axes, ...
            wheel_centers(wheel_index, 1) + [-0.052, 0.052], ...
            wheel_centers(wheel_index, 2) + [0, 0], ...
            "Color", colors.white, "LineWidth", 2);
    end
end
cart_body = rectangle(scene_axes, ...
    "Position", [-0.38, -0.09, 0.76, 0.32], ...
    "FaceColor", colors.garnet, "EdgeColor", colors.black, ...
    "LineWidth", 2.2);

pivot_y = 0.27;
trail = plot(scene_axes, nan, nan, ...
    "Color", colors.light_gray, "LineWidth", 2);
link_outline = plot(scene_axes, [0, 0], [pivot_y, pivot_y + parameters.length], ...
    "Color", colors.white, "LineWidth", 10);
link = plot(scene_axes, [0, 0], [pivot_y, pivot_y + parameters.length], ...
    "Color", colors.black, "LineWidth", 5);
pivot = plot(scene_axes, 0, pivot_y, "o", ...
    "MarkerSize", 10, "MarkerFaceColor", colors.white, ...
    "MarkerEdgeColor", colors.black, "LineWidth", 2);
bob = scatter(scene_axes, 0, pivot_y + parameters.length, 650, ...
    "o", "filled", "MarkerFaceColor", colors.atlantic, ...
    "MarkerEdgeColor", colors.black, "LineWidth", 2.5);

text(scene_axes, 0, 0.05, "cart", ...
    "Color", colors.white, "FontName", "Times New Roman", ...
    "FontSize", 13, "FontWeight", "bold", ...
    "HorizontalAlignment", "center");

state_text = text(scene_axes, -1.64, 1.36, "", ...
    "Color", colors.black, "FontName", "Times New Roman", ...
    "FontSize", 14, "FontWeight", "bold", ...
    "VerticalAlignment", "top", "BackgroundColor", colors.white, ...
    "Margin", 7, "EdgeColor", colors.dark_gray);
parameter_text = sprintf( ...
    "cart mass = %.1f kg    bob mass = %.1f kg\n" + ...
    "length = %.1f m    damping = %.2f N m s/rad\n" + ...
    "gravity = %.2f m/s^2    applied force = 0 N", ...
    parameters.cart_mass, parameters.pendulum_mass, ...
    parameters.length, parameters.damping, parameters.gravity);
text(scene_axes, -1.64, -0.69, parameter_text, ...
    "Color", colors.dark_gray, "FontName", "Times New Roman", ...
    "FontSize", 11, "VerticalAlignment", "bottom", ...
    "BackgroundColor", colors.white, "Margin", 6, ...
    "EdgeColor", colors.light_gray);

position_axes = nexttile(layout);
hold(position_axes, "on");
plot(position_axes, time, x_simulink, ...
    "Color", colors.garnet, "LineWidth", 1.8, ...
    "DisplayName", "Direct equations");
plot(position_axes, time, x_multibody, "--", ...
    "Color", colors.atlantic, "LineWidth", 1.8, ...
    "DisplayName", "Multibody");
position_cursor = xline(position_axes, 0, ...
    "Color", colors.black, "LineWidth", 1.4, "HandleVisibility", "off");
position_dot = plot(position_axes, 0, 0, "o", ...
    "Color", colors.black, "MarkerFaceColor", colors.atlantic, ...
    "MarkerSize", 7, "HandleVisibility", "off");
xlabel(position_axes, "time, s");
ylabel(position_axes, "cart position, m");
title(position_axes, "Cart translation");
legend(position_axes, "Location", "best");
style_axes(position_axes, colors);

angle_axes = nexttile(layout);
hold(angle_axes, "on");
plot(angle_axes, time, rad2deg(theta_simulink), ...
    "Color", colors.garnet, "LineWidth", 1.8, ...
    "DisplayName", "Direct equations");
plot(angle_axes, time, rad2deg(theta_multibody), "--", ...
    "Color", colors.atlantic, "LineWidth", 1.8, ...
    "DisplayName", "Multibody");
angle_cursor = xline(angle_axes, 0, ...
    "Color", colors.black, "LineWidth", 1.4, "HandleVisibility", "off");
angle_dot = plot(angle_axes, 0, rad2deg(theta_multibody(1)), "o", ...
    "Color", colors.black, "MarkerFaceColor", colors.atlantic, ...
    "MarkerSize", 7, "HandleVisibility", "off");
xlabel(angle_axes, "time, s");
ylabel(angle_axes, "angle from upright, deg");
title(angle_axes, "Pendulum angle");
style_axes(angle_axes, colors);

title_handle = title(layout, ...
    "Unforced Cart-Pendulum Motion | Simscape Multibody trajectory", ...
    "FontName", "Times New Roman", "FontSize", 18, ...
    "FontWeight", "bold", "Color", colors.black);
subtitle_handle = subtitle(layout, ...
    "The camera follows the cart. The ruler and world origin move by -x(t).", ...
    "FontName", "Times New Roman", "FontSize", 12, ...
    "Color", colors.dark_gray);

graphics.figure = figure_handle;
graphics.scene_axes = scene_axes;
graphics.world_ticks = world_ticks;
graphics.tick_lines = tick_lines;
graphics.tick_labels = tick_labels;
graphics.origin_marker = origin_marker;
graphics.origin_label = origin_label;
graphics.translation_line = translation_line;
graphics.translation_label = translation_label;
graphics.trail = trail;
graphics.link_outline = link_outline;
graphics.link = link;
graphics.pivot = pivot;
graphics.bob = bob;
graphics.state_text = state_text;
graphics.position_cursor = position_cursor;
graphics.position_dot = position_dot;
graphics.angle_cursor = angle_cursor;
graphics.angle_dot = angle_dot;
graphics.title_handle = title_handle;
graphics.subtitle_handle = subtitle_handle;
graphics.pivot_y = pivot_y;
graphics.length = parameters.length;
graphics.wheel_left = wheel_left;
graphics.wheel_right = wheel_right;
graphics.wheel_centers = wheel_centers;
graphics.wheel_radius = wheel_radius;
graphics.wheel_spokes = wheel_spokes;
graphics.cart_body = cart_body;
end

function update_animation_figure( ...
        graphics, current_time, time, x_multibody, theta_multibody, ...
        colors, playback_label)
current_x = interp1(time, x_multibody, current_time, "pchip");
current_theta = interp1(time, theta_multibody, current_time, "pchip");

bob_x = graphics.length * sin(current_theta);
bob_y = graphics.pivot_y + graphics.length * cos(current_theta);
graphics.link_outline.XData = [0, bob_x];
graphics.link_outline.YData = [graphics.pivot_y, bob_y];
graphics.link.XData = [0, bob_x];
graphics.link.YData = [graphics.pivot_y, bob_y];
graphics.bob.XData = bob_x;
graphics.bob.YData = bob_y;

trail_start = max(time(1), current_time - 1.25);
trail_times = linspace(trail_start, current_time, 35);
trail_theta = interp1(time, theta_multibody, trail_times, "pchip");
graphics.trail.XData = graphics.length * sin(trail_theta);
graphics.trail.YData = graphics.pivot_y + graphics.length * cos(trail_theta);

display_tick_positions = graphics.world_ticks - current_x;
for index = 1:numel(graphics.world_ticks)
    graphics.tick_lines(index).XData = ...
        [display_tick_positions(index), display_tick_positions(index)];
    graphics.tick_labels(index).Position(1) = display_tick_positions(index);
end
graphics.origin_marker.XData = -current_x;
graphics.origin_label.Position(1) = -current_x;
graphics.translation_line.XData = [-current_x, 0];
graphics.translation_label.Position(1) = -current_x / 2;
graphics.translation_label.String = sprintf("x(t) = %+.3f m", current_x);

wheel_angle = -current_x / graphics.wheel_radius;
spoke_radius = 0.052;
for wheel_index = 1:2
    for spoke_index = 1:2
        spoke_angle = wheel_angle + (spoke_index - 1) * pi / 2;
        spoke_dx = spoke_radius * cos(spoke_angle);
        spoke_dy = spoke_radius * sin(spoke_angle);
        graphics.wheel_spokes(wheel_index, spoke_index).XData = ...
            graphics.wheel_centers(wheel_index, 1) + [-spoke_dx, spoke_dx];
        graphics.wheel_spokes(wheel_index, spoke_index).YData = ...
            graphics.wheel_centers(wheel_index, 2) + [-spoke_dy, spoke_dy];
    end
end

graphics.state_text.String = sprintf( ...
    "t = %5.2f s\n" + ...
    "x = %+7.3f m\n" + ...
    "angle = %+7.1f deg", ...
    current_time, current_x, rad2deg(current_theta));
graphics.position_cursor.Value = current_time;
graphics.position_dot.XData = current_time;
graphics.position_dot.YData = current_x;
graphics.angle_cursor.Value = current_time;
graphics.angle_dot.XData = current_time;
graphics.angle_dot.YData = rad2deg(current_theta);

graphics.subtitle_handle.String = sprintf( ...
    "%s | Camera follows cart; ruler and origin move by -x(t)", ...
    playback_label);
graphics.scene_axes.Color = colors.sand;
end

function write_animation( ...
        figure_handle, graphics, frame_times, time, x_multibody, ...
        theta_multibody, colors, filename, frame_rate, playback_label)
writer = VideoWriter(filename, "MPEG-4");
writer.FrameRate = frame_rate;
writer.Quality = 95;
open(writer);
cleanup_writer = onCleanup(@() close(writer));

for index = 1:numel(frame_times)
    update_animation_figure( ...
        graphics, frame_times(index), time, x_multibody, ...
        theta_multibody, colors, playback_label);
    drawnow;
    writeVideo(writer, getframe(figure_handle));
end

close(writer);
clear cleanup_writer;
end

function style_axes(axes_handle, colors)
grid(axes_handle, "on");
axes_handle.FontName = "Times New Roman";
axes_handle.FontSize = 11;
axes_handle.LineWidth = 1;
axes_handle.XColor = colors.black;
axes_handle.YColor = colors.black;
axes_handle.GridColor = colors.light_gray;
axes_handle.GridAlpha = 0.7;
axes_handle.Color = colors.white;
axes_handle.Box = "on";
end
