"""
Reproduce Figure 5.3 from Sutton & Barto (Example 5.4):
Off-policy estimation of a single blackjack state value using
ordinary and weighted importance sampling.

Key detail from Example 5.4: "The data was generated by starting
in this state then choosing to hit or stick at random with equal
probability (the behavior policy)."

State evaluated: (player_sum=13, dealer_showing=2, usable_ace=True)
Target policy: stick on 20 or 21
Behavior policy: random (50/50 hit or stick)
"""

import numpy as np
import matplotlib.pyplot as plt

# ── Blackjack environment ──────────────────────────────────────
def draw_card():
    card = min(np.random.randint(1, 14), 10)
    return card


def hit(player_sum, usable_ace):
    card = draw_card()
    if card == 1 and player_sum + 11 <= 21:
        player_sum += 11
        usable_ace = True
    else:
        player_sum += card
    if player_sum > 21 and usable_ace:
        player_sum -= 10
        usable_ace = False
    bust = player_sum > 21
    return player_sum, usable_ace, bust


def play_episode_from_state(init_sum, dealer_showing, init_usable):
    """
    Play one episode starting from a fixed state, using the behavior
    policy (random 50/50 hit/stick).
    Returns: reward, list of (state, action) tuples.
    """
    player_sum = init_sum
    player_usable = init_usable
    dealer_hidden = draw_card()
    trajectory = []

    # Player's turn under behavior policy (random)
    while True:
        state = (player_sum, dealer_showing, player_usable)
        action = np.random.choice(['hit', 'stick'])
        trajectory.append((state, action))

        if action == 'stick':
            break
        else:
            player_sum, player_usable, bust = hit(player_sum, player_usable)
            if bust:
                return -1, trajectory

    # Dealer's turn
    dealer_sum = dealer_showing + dealer_hidden
    dealer_usable = (dealer_showing == 1 or dealer_hidden == 1)
    if dealer_usable and dealer_sum + 10 <= 21:
        dealer_sum += 10

    while dealer_sum < 17:
        card = draw_card()
        if card == 1 and dealer_sum + 11 <= 21:
            dealer_sum += 11
            dealer_usable = True
        else:
            dealer_sum += card
        if dealer_sum > 21 and dealer_usable:
            dealer_sum -= 10
            dealer_usable = False

    if dealer_sum > 21:
        reward = 1
    elif dealer_sum > player_sum:
        reward = -1
    elif dealer_sum < player_sum:
        reward = 1
    else:
        reward = 0

    return reward, trajectory


def target_policy_action(player_sum):
    """Action under target policy: stick on 20/21, else hit."""
    return 'stick' if player_sum >= 20 else 'hit'


def run_experiment(num_episodes, num_runs):
    """
    Run the off-policy estimation experiment.
    Every episode starts from the target state.
    Returns MSE arrays for ordinary and weighted IS.
    """
    ordinary_mse = np.zeros(num_episodes)
    weighted_mse = np.zeros(num_episodes)

    for run in range(num_runs):
        numerator_sum = 0.0   # sum of rho * G
        denominator_sum = 0.0  # sum of rho
        count = 0

        for ep in range(num_episodes):
            reward, trajectory = play_episode_from_state(13, 2, True)

            # Compute importance sampling ratio over the full trajectory
            rho = 1.0
            for state, action in trajectory:
                psum = state[0]
                target_action = target_policy_action(psum)
                # pi(a|s): 1 if action matches target, 0 otherwise
                if action != target_action:
                    rho = 0.0
                    break
                # b(a|s) = 0.5 always
                rho *= 1.0 / 0.5  # = 2.0

            G = reward  # gamma = 1
            numerator_sum += rho * G
            denominator_sum += rho
            count += 1

            v_ordinary = numerator_sum / count
            if denominator_sum > 0:
                v_weighted = numerator_sum / denominator_sum
            else:
                v_weighted = 0.0

            ordinary_mse[ep] += (v_ordinary - TRUE_VALUE) ** 2
            weighted_mse[ep] += (v_weighted - TRUE_VALUE) ** 2

        if (run + 1) % 10 == 0:
            print(f"  Run {run + 1}/{num_runs} complete")

    ordinary_mse /= num_runs
    weighted_mse /= num_runs

    return ordinary_mse, weighted_mse


# ── Main ───────────────────────────────────────────────────────
np.random.seed(42)

TRUE_VALUE = -0.27726
NUM_EPISODES = 10_000
NUM_RUNS = 100

print(f"Running {NUM_RUNS} independent runs of {NUM_EPISODES} episodes each...")
ordinary_mse, weighted_mse = run_experiment(NUM_EPISODES, NUM_RUNS)

# ── Plot ───────────────────────────────────────────────────────
garnet = '#73000A'
black90 = '#363636'
atlantic = '#466A9F'
horseshoe = '#65780B'

plt.rcParams.update({
    'font.family': 'serif',
    'text.color': black90,
    'axes.labelcolor': black90,
    'xtick.color': black90,
    'ytick.color': black90,
})

fig, ax = plt.subplots(figsize=(8, 5))

episodes = np.arange(1, NUM_EPISODES + 1)
ax.plot(episodes, ordinary_mse, color=garnet, linewidth=1.2, label='Ordinary importance sampling')
ax.plot(episodes, weighted_mse, color=horseshoe, linewidth=1.2, label='Weighted importance sampling')

ax.set_xscale('log')
ax.set_xlabel('Episodes (log scale)', fontsize=11)
ax.set_ylabel('Mean squared error\n(average over 100 runs)', fontsize=11)
ax.set_title('Exercise 5.7: Off-Policy Estimation of a Blackjack State Value',
             fontsize=13, fontweight='bold', color=garnet, pad=12)
ax.set_ylim(bottom=0, top=5)
ax.set_xlim(1, NUM_EPISODES)
ax.legend(fontsize=10, frameon=True, edgecolor=black90)
ax.tick_params(labelsize=9)

plt.tight_layout()
out_path = '/Volumes/MacShare/graduate-coursework/Sp26/CSCE775/course_notes/ch5_exercises/offpolicy_is_mse.png'
plt.savefig(out_path, dpi=200, bbox_inches='tight', facecolor='white')
plt.close()
print(f"\nSaved figure to {out_path}")

# Print stats
print(f"\nOrdinary IS — MSE at ep 1: {ordinary_mse[0]:.4f}, ep 100: {ordinary_mse[99]:.4f}, ep 10000: {ordinary_mse[-1]:.4f}")
print(f"Weighted IS — MSE at ep 1: {weighted_mse[0]:.4f}, ep 100: {weighted_mse[99]:.4f}, ep 10000: {weighted_mse[-1]:.4f}")
peak_idx = np.argmax(weighted_mse)
print(f"Weighted IS — Peak MSE: {weighted_mse[peak_idx]:.4f} at episode {peak_idx + 1}")
