// Section 04: Policy Optimization: TRPO, PPO, and Beyond

#set page(margin: 1in)
#set text(font: "New Computer Modern", size: 11pt)
#set par(leading: 0.65em, justify: true)

= 4. Policy Optimization: TRPO, PPO, and Beyond

The central challenge of policy gradient methods is that naive gradient ascent on the expected return can produce catastrophically large policy updates, destabilizing training and erasing previously learned behavior. The line of work from Trust Region Policy Optimization through Proximal Policy Optimization and its successors represents a sustained effort to tame this instability while keeping the algorithms practical at scale.

== 4.1 Trust Region Policy Optimization

The theoretical foundation for modern policy optimization was laid by Kakade and Langford [KakadeLangford2002], who showed that a conservative policy iteration scheme could guarantee monotonic improvement by bounding the divergence between successive policies. Schulman, Levine, Moritz, Jordan, and Abbeel [Schulman2015] extended this insight into a practical deep reinforcement learning algorithm, Trust Region Policy Optimization (TRPO). The key idea is to maximize a surrogate objective, the expected advantage of the new policy under the state distribution of the old policy, subject to a constraint that the KL divergence between the old and new policies remains below a threshold $delta$. Formally, at each iteration TRPO solves $max_theta hat(EE)[frac(pi_theta (a|s), pi_(theta_"old") (a|s)) hat(A)(s,a)]$ subject to $hat(EE)[D_"KL" (pi_(theta_"old") (dot|s) || pi_theta (dot|s))] <= delta$. This constrained optimization is solved approximately using the conjugate gradient method, which computes the natural gradient direction by solving a linear system involving the Fisher information matrix without ever forming or storing that matrix explicitly [Schulman2015]. The resulting update direction is then rescaled via a line search to satisfy the KL constraint. TRPO provided the first algorithm for deep policy optimization with a principled monotonic improvement guarantee, and it demonstrated strong empirical performance on continuous control benchmarks. However, the conjugate gradient computation and line search introduced significant computational overhead and implementation complexity, limiting its adoption in large-scale settings.

== 4.2 Generalized Advantage Estimation

A critical companion to trust-region methods is the question of how to estimate the advantage function $A(s,a)$ that appears in the policy gradient. Schulman, Moritz, Levine, Jordan, and Abbeel [Schulman2016] proposed Generalized Advantage Estimation (GAE), an exponentially weighted estimator that interpolates between high-bias, low-variance estimates (relying heavily on a learned value function) and low-bias, high-variance estimates (relying on full Monte Carlo returns). GAE introduces a parameter $lambda in [0,1]$ that controls this tradeoff. When $lambda = 0$, the estimator reduces to the one-step temporal difference residual, which has low variance but can be biased if the value function is inaccurate. When $lambda = 1$, it recovers the full Monte Carlo advantage, which is unbiased but high variance. In practice, values of $lambda$ between 0.9 and 0.99 are typical. The discount factor $gamma$ introduces a separate, complementary bias-variance tradeoff. Taking $gamma < 1$ introduces bias regardless of the value function's accuracy, while $lambda < 1$ introduces bias only when the value function is imperfect [Schulman2016]. GAE became a standard component in nearly all subsequent policy optimization algorithms, including PPO and its descendants.

== 4.3 Proximal Policy Optimization

Schulman, Wolski, Dhariwal, Radford, and Klimov [Schulman2017] introduced Proximal Policy Optimization (PPO) as a dramatically simpler alternative to TRPO. Rather than solving a constrained optimization problem with conjugate gradients, PPO enforces the trust region implicitly through a clipped surrogate objective. The probability ratio $r_t (theta) = pi_theta (a_t | s_t) slash pi_(theta_"old") (a_t | s_t)$ is clipped to the interval $[1 - epsilon, 1 + epsilon]$, and the objective takes the pessimistic (lower) bound of the clipped and unclipped terms. The resulting objective is $L^"CLIP" (theta) = hat(EE)_t [min(r_t (theta) hat(A)_t, "clip"(r_t (theta), 1 - epsilon, 1 + epsilon) hat(A)_t)]$. This formulation removes the need for conjugate gradient solvers, Fisher information matrices, and line searches. PPO can be implemented in a few dozen lines of code and optimized with standard stochastic gradient ascent over multiple epochs of minibatch updates on the same batch of collected trajectories. The clipping mechanism prevents the policy from changing too rapidly in any single update, achieving a similar effect to the KL constraint in TRPO but with far less computational cost.

PPO's simplicity, stability, and scalability made it the dominant policy optimization algorithm across robotics, game-playing, and, most consequentially, the reinforcement learning from human feedback (RLHF) pipelines used to align large language models [Schulman2017]. OpenAI's adoption of PPO for training ChatGPT cemented its status as the default choice for practitioners.

== 4.4 Implementation Matters

Despite PPO's apparent algorithmic elegance, a growing body of evidence suggests that its empirical dominance owes as much to engineering as to the clipped objective itself. Engstrom, Ilyas, Santurkar, Tsipras, Janoos, Rudolph, and Madry [Engstrom2020] conducted a systematic ablation study and found that code-level optimizations, details present only in reference implementations and not described in the original paper, are responsible for most of PPO's gain in cumulative reward over TRPO. These optimizations include global gradient clipping (constraining the L2 norm of the gradient to not exceed 0.5), value function clipping, reward normalization, observation normalization, orthogonal initialization, and learning rate annealing. When these implementation details were added to TRPO, the performance gap between the two algorithms largely vanished [Engstrom2020]. Huang, Dossa, Raffin, Kanervisto, and Wang [Huang2022] subsequently cataloged 37 distinct implementation details across different PPO application domains, further underscoring the gap between the algorithm as published and the algorithm as practiced. These findings raise an uncomfortable question for the field. If the theoretical contribution of the clipped surrogate is secondary to engineering details that accumulated through trial and error, then PPO's dominance may be partly an artifact of implementation maturity rather than algorithmic superiority.

== 4.5 Known Weaknesses of PPO

PPO's weaknesses are well documented. As an on-policy method, it must discard collected trajectories after each policy update, leading to poor sample efficiency in environments where interaction is expensive. The clipping parameter $epsilon$, learning rate, entropy bonus coefficient, number of minibatch epochs, and batch size all require careful tuning, and the sensitivity of performance to these hyperparameters makes reproducibility difficult. The conservative nature of the clipped update, while stabilizing, can also slow convergence and cause the policy to become trapped in local optima, particularly in high-dimensional or sparse-reward settings. Gaussian exploration noise, the default in continuous control, can be insufficient for complex state spaces, leading to inadequate exploration [Schulman2017].

== 4.6 Beyond PPO: GRPO, DAPO, and CAPO

The explosion of interest in training large language models for reasoning has driven a new generation of policy optimization algorithms that build on PPO's foundations while addressing its specific limitations in the LLM setting. Group Relative Policy Optimization (GRPO), introduced by Shao, Wang, Zhu, and Xu in the DeepSeekMath work [Shao2024], eliminates the critic network entirely. Instead of training a separate value function to estimate baselines, GRPO generates a group of candidate responses for each prompt and computes advantages relative to the group's mean reward. This reduces memory overhead by approximately 50\% compared to PPO, a critical consideration when the policy itself is a multi-billion-parameter language model. GRPO retains the clipped surrogate objective from PPO but replaces the learned baseline with a sample-based one. DeepSeek-R1 demonstrated that GRPO could train competitive reasoning models from scratch using only reinforcement learning with verifiable rewards [DeepSeek2025].

DAPO (Decoupled Clip and Dynamic Sampling Policy Optimization), developed by Yu, Zhang, Zhu, Yuan, and colleagues at ByteDance Seed and Tsinghua University [Yu2025], addresses the entropy collapse problem that arises during long chain-of-thought reinforcement learning. DAPO decouples the lower and upper clipping bounds, increasing the upper bound $epsilon_"high"$ to allow low-probability tokens more room to increase in likelihood, thereby preserving diversity in the policy's output distribution. Dynamic sampling filters out prompts for which the current policy achieves either perfect or zero accuracy, ensuring that every training batch contains prompts with effective gradient signal. Token-level policy gradient loss and overlong reward shaping further stabilize training. DAPO achieved 50\% accuracy on AIME 2024 with Qwen2.5-32B, surpassing DeepSeek-R1-Zero-Qwen-32B while requiring 50\% fewer training steps [Yu2025].

Most recently, Melo, Abate, and Gal proposed Curvature-Aware Policy Optimization (CAPO), published at ICLR 2026 [Melo2026]. CAPO exploits an inexpensive approximation of second-order curvature information to identify and mask out tokens whose gradient contributions would destabilize the update. The method achieves up to a 30-fold improvement in sample efficiency over standard GRPO on mathematical reasoning benchmarks, with minimal intervention, rejecting fewer than 8\% of tokens and adding negligible computational overhead. CAPO also provides monotonic improvement guarantees under practical assumptions, reconnecting modern LLM-focused policy optimization with the theoretical tradition of TRPO. Extensions to other base algorithms, including Dr.GRPO and REINFORCE, yield Dr.CAPO and ReinCAPO, demonstrating the generality of curvature-aware masking [Melo2026].

== 4.7 Synthesis

The trajectory from TRPO through PPO and into GRPO, DAPO, and CAPO reveals a field in tension between theoretical rigor and engineering pragmatism. TRPO offered monotonic improvement guarantees but was too complex for widespread adoption. PPO traded theoretical elegance for simplicity and became dominant, yet its success depended heavily on implementation details that were never part of the published algorithm [Engstrom2020]. The LLM era has forced a rethinking of these tradeoffs. Critic-free methods like GRPO reduce memory costs, entropy-aware methods like DAPO prevent mode collapse during long-horizon reasoning, and curvature-aware methods like CAPO recover sample efficiency and stability guarantees without the computational burden of full second-order optimization. Whether the next generation of policy optimization algorithms will achieve a cleaner separation between algorithmic contribution and engineering artifact remains an open question.

#pagebreak()

== References

+ #label("KakadeLangford2002") S. Kakade and J. Langford. "Approximately Optimal Approximate Reinforcement Learning." _Proceedings of the 19th International Conference on Machine Learning (ICML)_, pp. 267--274, 2002.

+ #label("Schulman2015") J. Schulman, S. Levine, P. Moritz, M. Jordan, and P. Abbeel. "Trust Region Policy Optimization." _Proceedings of the 32nd International Conference on Machine Learning (ICML)_, pp. 1889--1897, 2015.

+ #label("Schulman2016") J. Schulman, P. Moritz, S. Levine, M. Jordan, and P. Abbeel. "High-Dimensional Continuous Control Using Generalized Advantage Estimation." _Proceedings of the 4th International Conference on Learning Representations (ICLR)_, 2016.

+ #label("Schulman2017") J. Schulman, F. Wolski, P. Dhariwal, A. Radford, and O. Klimov. "Proximal Policy Optimization Algorithms." _arXiv preprint arXiv:1707.06347_, 2017.

+ #label("Engstrom2020") L. Engstrom, A. Ilyas, S. Santurkar, D. Tsipras, F. Janoos, L. Rudolph, and A. Madry. "Implementation Matters in Deep Policy Gradients: A Case Study on PPO and TRPO." _Proceedings of the 8th International Conference on Learning Representations (ICLR)_, 2020.

+ #label("Huang2022") S. Huang, R. F. J. Dossa, A. Raffin, A. Kanervisto, and W. Wang. "The 37 Implementation Details of Proximal Policy Optimization." _ICLR Blog Track_, 2022.

+ #label("Shao2024") Z. Shao, P. Wang, Q. Zhu, and R. Xu et al. "DeepSeekMath: Pushing the Limits of Mathematical Reasoning in Open Language Models." _arXiv preprint arXiv:2402.03300_, 2024.

+ #label("DeepSeek2025") DeepSeek-AI. "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning." _arXiv preprint arXiv:2501.12948_, 2025.

+ #label("Yu2025") Q. Yu, Z. Zhang, R. Zhu, Y. Yuan et al. "DAPO: An Open-Source LLM Reinforcement Learning System at Scale." _Advances in Neural Information Processing Systems (NeurIPS)_, 2025.

+ #label("Melo2026") L. C. Melo, A. Abate, and Y. Gal. "Stabilizing Policy Gradients for Sample-Efficient Reinforcement Learning in LLM Reasoning." _Proceedings of the 14th International Conference on Learning Representations (ICLR)_, 2026.
