function add_multibody_learning_geometry(model_name, parameters)
%ADD_MULTIBODY_LEARNING_GEOMETRY Add visible native Multibody geometry.

arguments
    model_name (1, 1) string
    parameters (1, 1) struct
end

load_system("sm_lib");
load_system(model_name);

rod_transform_path = model_name + "/Learning rod center";
rod_path = model_name + "/Visible pendulum rod";
ruler_subsystem_path = model_name + "/World ruler";
ruler_transform_path = model_name + "/World ruler position";
ruler_path = model_name + "/World ruler rail";

paths_to_replace = [
    rod_transform_path
    rod_path
    ruler_subsystem_path
    ruler_transform_path
    ruler_path
];
for index = 1:numel(paths_to_replace)
    if getSimulinkBlockHandle(paths_to_replace(index)) ~= -1
        delete_block(paths_to_replace(index));
    end
end
for index = 1:29
    tick_transform_path = model_name + sprintf("/Ruler tick %02d position", index);
    tick_path = model_name + sprintf("/Ruler tick %02d", index);
    if getSimulinkBlockHandle(tick_transform_path) ~= -1
        delete_block(tick_transform_path);
    end
    if getSimulinkBlockHandle(tick_path) ~= -1
        delete_block(tick_path);
    end
end

cart_path = model_name + "/Cart mass";
bob_path = model_name + "/Pendulum point mass";
default_solid_color = "[0.5 0.5 0.5]";
set_param(cart_path, "GraphicDiffuseColor", default_solid_color);
set_param(bob_path, "GraphicDiffuseColor", default_solid_color);

add_block( ...
    "sm_lib/Frames and Transforms/Rigid Transform", ...
    rod_transform_path, ...
    "Position", [770, 90, 875, 165]);
set_param(rod_transform_path, ...
    "TranslationMethod", "Cartesian", ...
    "TranslationCartesianOffset", sprintf("[-%.17g 0 0]", parameters.ell / 2), ...
    "TranslationCartesianOffsetUnits", "m", ...
    "RotationMethod", "StandardAxis", ...
    "RotationStandardAxis", "+Y", ...
    "RotationAngle", "-90", ...
    "RotationAngleUnits", "deg");

add_block( ...
    "sm_lib/Body Elements/Cylindrical Solid", ...
    rod_path, ...
    "Position", [925, 90, 1045, 165]);
set_param(rod_path, ...
    "Orientation", "left", ...
    "CylinderRadius", "0.006", ...
    "CylinderLength", num2str(parameters.ell, 17), ...
    "InertiaType", "Custom", ...
    "Mass", "1e-9", ...
    "CenterOfMass", "[0 0 0]", ...
    "MomentsOfInertia", "[1e-12 1e-12 1e-12]", ...
    "ProductsOfInertia", "[0 0 0]", ...
    "GraphicDiffuseColor", default_solid_color);

revolute_ports = get_param(model_name + "/Damped pivot", "PortHandles");
rod_transform_ports = get_param(rod_transform_path, "PortHandles");
rod_ports = get_param(rod_path, "PortHandles");
connect_if_unconnected( ...
    model_name, revolute_ports.RConn(1), rod_transform_ports.LConn(1));
connect_if_unconnected( ...
    model_name, rod_transform_ports.RConn(1), rod_ports.RConn(1));

add_block("simulink/Ports & Subsystems/Subsystem", ...
    ruler_subsystem_path, "Position", [1100, 70, 1230, 140]);
delete_block(ruler_subsystem_path + "/In1");
delete_block(ruler_subsystem_path + "/Out1");

ruler_world_path = ruler_subsystem_path + "/World Frame";
ruler_solver_path = ruler_subsystem_path + "/Solver Configuration";
ruler_transform_path = ruler_subsystem_path + "/Ruler position";
ruler_path = ruler_subsystem_path + "/Rail";

add_block("sm_lib/Frames and Transforms/World Frame", ...
    ruler_world_path, "Position", [40, 55, 100, 115]);
add_block("nesl_utility/Solver Configuration", ...
    ruler_solver_path, "Position", [40, 655, 135, 715]);
add_block("sm_lib/Frames and Transforms/Rigid Transform", ...
    ruler_transform_path, "Position", [150, 50, 255, 120]);
set_param(ruler_transform_path, ...
    "TranslationMethod", "Cartesian", ...
    "TranslationCartesianOffset", "[0 0 -0.15]", ...
    "TranslationCartesianOffsetUnits", "m");

add_block("sm_lib/Body Elements/Brick Solid", ...
    ruler_path, "Position", [305, 50, 420, 120]);
set_param(ruler_path, ...
    "BrickDimensions", "[1.4 0.20 0.04]", ...
    "BasedOnType", "Mass", ...
    "Mass", "0.1", ...
    "GraphicDiffuseColor", default_solid_color);

ruler_world_ports = get_param(ruler_world_path, "PortHandles");
ruler_solver_ports = get_param(ruler_solver_path, "PortHandles");
ruler_transform_ports = get_param(ruler_transform_path, "PortHandles");
ruler_ports = get_param(ruler_path, "PortHandles");
connect_if_unconnected( ...
    ruler_subsystem_path, ...
    ruler_world_ports.RConn(1), ruler_solver_ports.RConn(1));
connect_if_unconnected( ...
    ruler_subsystem_path, ...
    ruler_world_ports.RConn(1), ruler_transform_ports.LConn(1));
connect_if_unconnected( ...
    ruler_subsystem_path, ...
    ruler_transform_ports.RConn(1), ruler_ports.RConn(1));

tick_positions = -0.6:0.1:0.6;
for index = 1:numel(tick_positions)
    tick_transform_path = ruler_subsystem_path + ...
        sprintf("/Tick %02d position", index);
    tick_path = ruler_subsystem_path + sprintf("/Tick %02d", index);
    row = mod(index - 1, 7);
    column = floor((index - 1) / 7);
    transform_position = [40 + 310 * column, 180 + 85 * row, ...
        145 + 310 * column, 245 + 85 * row];
    solid_position = [190 + 310 * column, 180 + 85 * row, ...
        305 + 310 * column, 245 + 85 * row];

    add_block( ...
        "sm_lib/Frames and Transforms/Rigid Transform", ...
        tick_transform_path, ...
        "Position", transform_position);
    set_param(tick_transform_path, ...
        "TranslationMethod", "Cartesian", ...
        "TranslationCartesianOffset", sprintf("[%.17g 0 -0.121]", tick_positions(index)), ...
        "TranslationCartesianOffsetUnits", "m");

    add_block( ...
        "sm_lib/Body Elements/Brick Solid", ...
        tick_path, ...
        "Position", solid_position);
    if abs(tick_positions(index)) < 1e-12
        tick_width = 0.025;
    elseif abs(2 * tick_positions(index) - round(2 * tick_positions(index))) < 1e-12
        tick_width = 0.022;
    else
        tick_width = 0.012;
    end
    set_param(tick_path, ...
        "BrickDimensions", sprintf("[%.17g 0.22 0.018]", tick_width), ...
        "BasedOnType", "Mass", ...
        "Mass", "0.001", ...
        "GraphicDiffuseColor", default_solid_color);

    tick_transform_ports = get_param(tick_transform_path, "PortHandles");
    tick_ports = get_param(tick_path, "PortHandles");
    connect_if_unconnected( ...
        ruler_subsystem_path, ...
        ruler_world_ports.RConn(1), tick_transform_ports.LConn(1));
    connect_if_unconnected( ...
        ruler_subsystem_path, ...
        tick_transform_ports.RConn(1), tick_ports.RConn(1));
end

ruler_mask = Simulink.Mask.create(ruler_subsystem_path);
ruler_mask.Display = "disp('World ruler')";
set_param(ruler_subsystem_path, "ShowName", "off");

set_param(model_name, "SimMechanicsOpenEditorOnUpdate", "on");
save_system(model_name);
end

function connect_if_unconnected(model_name, source_port, destination_port)
if get_param(destination_port, "Line") == -1
    add_line(model_name, source_port, destination_port, "autorouting", "on");
end
end
