#import "figures.typ" as f
#let validation = json("data/validation.json")
#let metrics = validation.metrics
#let fmt = f.fmt
#set document(title: "Twin-Thruster Boat Dynamics and Control Feasibility", author: "J.C. Vaught", date: datetime(year: 2026, month: 10, day: 8))
#set page(paper: "us-letter", margin: (x: 0.85in, top: 0.8in, bottom: 0.8in),
  header: [#text(size: 9pt)[J.C. Vaught] #h(1fr) #text(size: 9pt)[EMCH 792 · Boat control]],
  footer: context align(center, text(size: 9pt, counter(page).display("1"))))
#set text(font: ("Times New Roman", "New Computer Modern"), size: 11pt, lang: "en")
#set par(justify: true, leading: 0.57em, spacing: 0.75em)
#set heading(numbering: "1.")
#show heading: set text(size: 12pt, weight: "bold")
#show heading: set block(above: 12pt, below: 7pt)
#show figure.caption: set text(size: 9pt)
#set figure(gap: 7pt)
#set math.equation(numbering: "(1)")
#show table: set text(size: 9.5pt, hyphenate: false)
#let tbl(columns, ..cells) = table(columns: columns, inset: (x: 6pt, y: 5pt), stroke: none,
  table.hline(stroke: 0.8pt), ..cells, table.hline(stroke: 0.8pt))
#let section(title) = heading(title)

#align(center)[
  #text(size: 21pt)[Twin-Thruster Boat Dynamics]
  #v(3pt)
  #text(size: 18pt)[and Control Feasibility]
  #v(9pt)
  J.C. Vaught #linebreak()
  EMCH 792 · Dr. Yi Wang #linebreak()
  October 8, 2026
]
#v(5pt)
#line(length: 100%, stroke: 1pt + f.garnet)

= Project objective
An autonomous surface vessel must reach a target while wind and water disturbances change its motion. Two independent thrusters provide forward force and yaw moment, but neither produces direct lateral force. This project therefore examines how thrust, drag, and turning interact before selecting a feedback controller.

The simulations reconstruct the seven experiments in the original presentation @Vaught2026BoatControl. Equal thrust produces a terminal surge speed of #fmt(metrics.surge_terminal_m_s, digits: 3) m/s. A 5 m/s crosswind produces #fmt(metrics.drift_60s_m) m of drift in 60 s. A thrust schedule that reaches a target 20 m ahead in calm conditions instead leaves errors of #fmt(metrics.blind_90s_errors_m.crosswind) m in crosswind and #fmt(metrics.blind_90s_errors_m.headwind) m in headwind after 90 s. These results establish the need for feedback and a guidance strategy that accounts for lateral underactuation.

#figure(f.hull(), caption: [Planar twin-thruster configuration. Positive surge points forward and positive sway points left. Thruster separation is measured between force lines.]) <hull>

#tbl((1.1fr, 1fr, 1.7fr),
  table.header([Quantity], [Value], [Role]), table.hline(stroke: 0.5pt),
  [Hull length], [4.9 m], [Geometry shown in the slides],
  [Mass, $m$], [180 kg], [Translational inertia],
  [Yaw inertia, $I_z$], [446 kg m²], [Rotational inertia],
  [Thruster separation, $B$], [2.4 m], [Yaw moment arm],
  [Each thruster], [−100 to 250 N], [Reverse and forward force limits],
)

#pagebreak()
= Planar model and simulation method
The geometry in @hull defines three degrees of freedom. The inertial pose is $bold(eta) = (x,y,psi)^T$, and the body velocity is $bold(nu) = (u,v,r)^T$. Here, $x$ and $y$ denote east and north position, $psi$ denotes heading measured counterclockwise from east, and $u$, $v$, and $r$ denote surge speed, sway speed, and yaw rate. This planar reduction follows the rigid-body, Coriolis, and damping structure of the marine-craft equations @Fossen2026MarineModel.

The heading rotates body velocity into the inertial frame. The resulting kinematics are
$ dot(x) = u cos psi - v sin psi, quad dot(y) = u sin psi + v cos psi, quad dot(psi) = r. $ <kinematics>
The left and right thrusters apply $T_L$ and $T_R$. Because their force lines are separated by $B$, the force and moment allocation is
$ tau_u = T_L + T_R, quad tau_v = 0, quad tau_r = B/2 (T_R-T_L). $ <allocation>
The nonlinear equations retain the coupling generated by rotation. With body-frame wind forces $F_u$ and $F_v$, the equations are
$ m dot(u) = m v r + T_L + T_R - d_1 u - d_2 u abs(u) + F_u, $ <surge>
$ m dot(v) = -m u r - d_v v + F_v, $ <sway>
$ I_z dot(r) = B/2 (T_R - T_L) - d_r r. $ <yaw>

#tbl((1fr, 1fr, 1.65fr),
  table.header([Coefficient], [Value], [Reconstruction basis]), table.hline(stroke: 0.5pt),
  [Linear surge drag, $d_1$], [51.3 N s/m], [Stated in the slides],
  [Quadratic surge drag, $d_2$], [72.4 N s²/m²], [Stated in the slides],
  [Linear sway drag, $d_v$], [40 N s/m], [Stated in the slides],
  [Linear yaw drag, $d_r$], [400 N m s], [Inferred from yaw step and pulse],
  [5 m/s wind force], [15.3 N], [Slide-plot value],
)

For a constant inertial wind force $(F_x,F_y)$, the body components are $F_u = F_x cos psi + F_y sin psi$ and $F_v = -F_x sin psi + F_y cos psi$. The crosswind acts along positive $y$; the headwind acts along negative $x$. Wind applies no yaw moment in this model. Added mass, wave excitation, and vertical motion are outside the slide model.

The original simulation source was unavailable, so the implementation is reconstructed from the equations, captions, and embedded plot images. SciPy integrates the six-state system with relative tolerance $10^(-10)$, absolute tolerance $10^(-12)$, and a maximum step of 0.05 s. Integration restarts at every thrust switch, and results are sampled at 0.05 s intervals. The next sections apply the same model to each slide experiment.

#pagebreak()
= Steady and differential thrust
The first experiment isolates surge motion. Both thrusters step to 100 N at $t = 1$ s from rest. As speed rises, drag increases until it balances the 200 N total force. Setting $dot(u)=0$ in @surge gives the terminal-speed relation
$ d_2 u_infinity^2 + d_1 u_infinity = 200, quad u_infinity = (-d_1 + sqrt(d_1^2 + 800 d_2))/(2 d_2) = 1.3451 "m/s". $
#figure(f.equal-step(), caption: [Equal thrust produces monotonic surge acceleration toward the drag-balanced speed. Sway and yaw remain zero.]) <equal>

The second experiment applies $T_L=100$ N and $T_R=150$ N at $t=1$ s. The total force rises to 250 N, and the 50 N thrust difference produces a 60 N m yaw moment. Consequently, the terminal yaw rate is $r_infinity = 60/400 = 0.15$ rad/s. Rotation induces negative sway through the $-u r$ term, which feeds back into surge through $v r$.

#figure(f.differential(), caption: [Differential thrust couples forward motion and turning. Translational speed and yaw rate use separate axes because their units differ.]) <differential>

#grid(columns: (1fr, 1fr), column-gutter: 20pt,
  align(center, f.turning-path()),
  [
    #v(12pt)
    The coupled steady speeds are $u = 1.4391$ m/s and $v = -0.9714$ m/s. From @sway, $v_infinity = -m u_infinity r_infinity/d_v$, so the lateral speed persists while the boat turns.

    The corresponding path approaches a circular orbit. At 60 s, the boat is at $(16.49,15.73)$ m, consistent with the endpoint shown in the presentation. Equal scaling of both position axes preserves the path geometry.

    The steady turning radius is approximately $sqrt(u_infinity^2+v_infinity^2)/abs(r_infinity) = 11.58$ m. A constant thrust difference therefore creates sustained turning rather than convergence to a target.
  ],
)

#pagebreak()
= Pulse response and free decay
The steady turning response establishes the velocity coupling. A short asymmetric pulse then shows how that coupling persists after thrust is removed. The boat starts from rest, receives $T_L=150$ N and $T_R=-100$ N over $1 <= t < 2$ s, and coasts for the remainder of the 30 s experiment.

#figure(f.pulse(), caption: [A one-second pulse creates a sharp yaw response and a slower sway response. The yaw panel enlarges the first 12 s to expose the transient.]) <pulse>

The pulse applies 50 N of surge force and −300 N m of yaw moment. The reconstructed yaw minimum is #fmt(metrics.pulse_min_r_rad_s, digits: 4) rad/s, while sway reaches #fmt(metrics.pulse_peak_v_m_s, digits: 4) m/s. Positive sway follows from $-u r$ when surge is positive and yaw rate is negative. Its peak occurs after the pulse because yaw-induced translation and sway damping act on different time scales.

The unforced experiment starts with $(u,v,r)=(1,0.5,0.5)$ and applies zero thrust for 30 s. Each velocity approaches zero, as shown below, but the final position and heading depend on the integrated transient.

#figure(f.decay(), caption: [Free decay dissipates velocity without restoring the initial pose. Yaw decays faster than sway.]) <decay>

This behavior follows directly from kinetic energy. Defining $E = m(u^2+v^2)/2 + I_z r^2/2$, substitution of @surge, @sway, and @yaw under zero thrust and zero wind gives
$ dot(E) = -d_1 u^2 - d_2 abs(u)^3 - d_v v^2 - d_r r^2 <= 0. $
The rotational coupling terms cancel because they transfer energy between surge and sway. Damping removes the remaining energy. Thus, the velocity equilibrium is attracting, while position has no restoring term. This distinction explains why the boat can stop moving without reaching the desired location.

#pagebreak()
= Phase-plane behavior and wind drift
The decay experiment motivates a closer view of the sway–yaw subsystem. Holding surge at a fixed value $U$ produces the reduced equations $dot(v)=-d_v v/m-U r$ and $dot(r)=-d_r r/I_z$. These phase portraits use 25 initial pairs spanning $v_0 in [-1,1]$ m/s and $r_0 in [-0.5,0.5]$ rad/s. Surge is frozen for this diagnostic and is not integrated as a third dynamic variable.

#figure(f.phase-pair(), caption: [Sway–yaw trajectories converge to the origin for both frozen surge speeds. Nonzero surge bends the trajectories through yaw–sway coupling.]) <phase>

The reduced subsystem has decay rates $-d_v/m=-0.2222$ s⁻¹ and $-d_r/I_z=-0.8969$ s⁻¹. Both remain negative when $U$ changes, so surge modifies the transient geometry without changing these two eigenvalues. The corresponding time constants are 4.5 s for sway and 1.115 s for yaw.

Wind changes the equilibrium rather than simply delaying decay. With no thrust, zero initial velocity, and 15.3 N of lateral wind force, @sway becomes $m dot(v)+d_v v=15.3$. Its solution is
$ v(t) = F_y/d_v (1-e^(-t/tau_v)), quad y(t) = F_y/d_v [t-tau_v(1-e^(-t/tau_v))], quad tau_v=m/d_v. $

#figure(f.wind(), caption: [A constant crosswind creates a bounded lateral velocity and unbounded position drift. The same input gives both curves.]) <wind>

The lateral equilibrium is $v_infinity=15.3/40=0.3825$ m/s. Integrating this motion produces #fmt(metrics.drift_60s_m, digits: 4) m of displacement at 60 s. Once the velocity settles, position grows almost linearly. The absence of direct lateral thrust therefore becomes a guidance problem, even when all velocity transients are damped.

#pagebreak()
= Open-loop target approach
The wind-drift result predicts failure of a schedule calibrated only for calm water. To test that consequence, the boat starts at the origin with zero velocity and aims at $(20,0)$ m. Both thrusters apply 100 N for 13.8329 s and then switch to zero. This schedule is reconstructed from the calm slide trace because the original switching schedule was not stated. The 200 N force is supported by a trace fit of 200.58 N; the cutoff is selected so that the thrust interval plus the subsequent coast covers 20 m.

#figure(f.schedule(), caption: [Reconstructed input used unchanged in calm, crosswind, and headwind environments.]) <schedule>

After the switch, the calm-water coast distance from speed $u_s$ is $m/d_2 ln(1+d_2 u_s/d_1)$. Adding it to the distance accumulated during thrust gives the selected 20 m endpoint. The wind cases then use the same schedule without further fitting.

#figure(f.blind(), caption: [The nominal schedule reaches the calm-water target but accumulates large errors under constant wind. The path panel uses separate axis scales; the distance panel gives the physical error.]) <blind>

#tbl((1.2fr, 1fr, 1fr, 1fr),
  table.header([Environment], [$x(90)$ (m)], [$y(90)$ (m)], [Target error (m)]), table.hline(stroke: 0.5pt),
  [Calm], [20.0000], [0.0000], [0.0000],
  [Crosswind], [20.0000], [32.7038], [32.7038],
  [Headwind], [2.4482], [0.0000], [17.5518],
)

Crosswind preserves the nominal forward motion because heading remains zero, but lateral displacement reaches 32.70 m. Headwind reduces progress during thrust and drives the boat backward after thrust ends. The final headwind surge speed is −0.2261 m/s. Both cases show why a preplanned input alone cannot regulate target distance in a changing environment.

#pagebreak()
= Reproduction and numerical verification
The preceding experiments retain the slide parameters and reproduce their visible trajectories. To quantify agreement, the embedded images are extracted unchanged from the presentation, and colored traces are digitized using recorded axis calibrations. Legend regions are excluded. The root-mean-square (RMS) differences below compare reconstructed curves with the retained raster samples; the largest is #fmt(metrics.max_slide_rmse_pixels) pixel.

#tbl((1.65fr, 0.65fr, 1fr, 0.6fr),
  table.header([Slide curve], [Samples], [RMS in physical units], [RMS pixels]), table.hline(stroke: 0.5pt),
  ..validation.source_comparisons.map(row => {
    let names = (
      equal_u: [Equal thrust, $u$], differential_u: [Differential thrust, $u$],
      differential_v: [Differential thrust, $v$], differential_r: [Differential thrust, $r$],
      pulse_v: [Pulse, $v$], pulse_r: [Pulse, $r$], decay_u: [Free decay, $u$],
      decay_v: [Free decay, $v$], decay_r: [Free decay, $r$], wind_y: [Crosswind drift, $y$],
      blind_calm_distance: [Target distance, calm], blind_crosswind_distance: [Target distance, crosswind],
      blind_headwind_distance: [Target distance, headwind],
    )
    (names.at(row.trace), [#row.samples], [#fmt(row.rmse, digits: 5) #row.unit], [#fmt(row.rmse_pixels, digits: 3)])
  }).flatten(),
)

#figure(f.overlays(), caption: [Representative overlays show the rebuilt curves against sampled slide traces. The comparison uses every retained sample; only every tenth marker is displayed.]) <overlays>

Independent checks support the numerical implementation. The surge step agrees with its exact scalar solution to $3.18 times 10^(-11)$ m/s, the yaw step agrees to $3.46 times 10^(-13)$ rad/s, and the wind-drift solution agrees to $2.40 times 10^(-14)$ m. Halving the maximum integration step changes no state component by more than $2.38 times 10^(-10)$ in its corresponding units. The free-decay energy decreases monotonically, and every thrust input remains within the stated limits.

The accompanying project stores the simulation code, input schedule, numerical checks, digitized samples, source-image hashes, and figure source. Consequently, the report can be rebuilt from the retained presentation rather than depending on inaccessible plotting code. Yaw damping and the blind schedule remain explicitly identified as reconstructed quantities.

#pagebreak()
= Feedback architecture and control feasibility
The open-loop errors motivate the feedback architecture proposed in the presentation. Satellite position, an inertial measurement unit, and camera target measurements feed a state estimator. Guidance converts target geometry into a feasible motion reference, and the controller commands the two thrusters from the estimated state.

#figure(f.feedback(), caption: [Proposed guidance, control, and estimation architecture. The experiments in this report characterize the boat; they do not implement this closed loop.]) <feedback>

The proposed controller is a linear-quadratic regulator (LQR). For the local model $dot(bold(z)) = A bold(z) + G bold(a)$, $bold(z)$ contains the six state perturbations and $bold(a)$ contains the two thrust perturbations. The regulator minimizes $J = integral_0^infinity (bold(z)^T Q bold(z)+bold(a)^T R bold(a)) dif t$, where $Q$ weights state error and $R$ weights input effort. A stabilizing solution requires a stabilizable input pair @MathWorks2026LQR. The operating point therefore determines whether LQR can address the full pose objective.

At rest, the linearized model gives $dot(y)=v$ and $dot(v)=-d_v v/m$, with neither equation directly driven by the thrusters. The six-state controllability matrix has rank four, and the uncontrolled lateral-position mode has eigenvalue zero. A full-state linear regulator about rest cannot stabilize this mode. At a straight-running reference with $U=1$ m/s, the terms $dot(y)=U psi+v$ and $dot(v)=-d_v v/m-U r$ restore the necessary yaw–lateral coupling, and the rank becomes six.

This finding supports a motion-based guidance strategy with a controller designed around a running reference. It also explains why arbitrary position and heading cannot both be held at rest under crosswind. At zero velocity and the nominal heading, the nonzero lateral wind force has no opposing actuator force. A heading adjustment or continued maneuvering is required.

#tbl((1.35fr, 1fr, 1fr),
  table.header([Design objective from the slides], [Target], [Status]), table.hline(stroke: 0.5pt),
  [Recovery from 5 m and 30° error], [Settling under 30 s], [Proposed],
  [Transient overshoot], [Under 10%], [Proposed],
  [Position error in 5 m/s wind], [Under 0.3 m], [Proposed],
  [Heading error in 5 m/s wind], [Under 15°], [Proposed],
  [Each thruster command], [−100 to 250 N], [Verified for open-loop tests],
)

The reconstructed results establish the model response and the control-design constraint. Damping stabilizes velocity, differential thrust generates sustained coupled motion, and constant wind produces persistent target error. The next design step is therefore to combine feasible guidance, state estimation, and constrained feedback, then evaluate the stated recovery and disturbance-rejection targets in closed-loop simulations.

#v(3pt)
#bibliography("references.bib", style: "ieee", title: [References])
